stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    - experiments/data_to_mongodb.py
    outs:
    - data/raw
    
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/raw
    outs:
    - data/split
    params:
    - data_preprocessing.test_size

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - data/split
    outs:
    - data/cleaned

  train_evaluate_model:
    cmd: python src/train_evaluate_model.py
    deps:
    - data/cleaned
    - src/train_evaluate_model.py
    outs:
    - models/model.pkl
    - metrics/result.json
    params:
    - train_evaluate_model.n_estimators
    - train_evaluate_model.max_depth

  frontend_api:
    cmd : uvicorn src.frontend_api:app --reload
    deps:
    - models/model.pkl
    - src/frontend_api.py